import {
  MinecraftServerInstance,
  MinecraftServerMetrics,
  MinecraftConsoleLog,
  ServerFileItem,
  MinecraftPluginItem,
  MinecraftModItem,
  MinecraftWorld,
} from './types.ts';
import { MinecraftLoader } from './minecraftLoaders.ts';

export const POPULAR_PLUGINS: Omit<MinecraftPluginItem, 'id' | 'enabled'>[] = [
  {
    name: 'EssentialsX',
    version: '2.20.1',
    author: 'EssentialsX Team',
    description: 'Essential server commands, warps, homes, economy integration, kits, and player management.',
    fileName: 'EssentialsX-2.20.1.jar',
    category: 'administration',
  },
  {
    name: 'LuckPerms',
    version: '5.4.102',
    author: 'Luck',
    description: 'An advanced permissions plugin with web editor, rank hierarchies, and fast SQL/local storage.',
    fileName: 'LuckPerms-Bukkit-5.4.102.jar',
    category: 'administration',
  },
  {
    name: 'WorldEdit',
    version: '7.3.0',
    author: 'EngineHub',
    description: 'In-game Minecraft map editor with brushes, schematics, terraforming, and mass block replacement.',
    fileName: 'worldedit-bukkit-7.3.0.jar',
    category: 'world',
  },
  {
    name: 'Vault',
    version: '1.7.3',
    author: 'Sleakes',
    description: 'Universal Permissions, Chat, and Economy API bridge for Bukkit and Paper plugins.',
    fileName: 'Vault-1.7.3.jar',
    category: 'economy',
  },
  {
    name: 'CoreProtect',
    version: '22.4',
    author: 'Intelli',
    description: 'Fast, efficient data logging, block grief rollback, chest inspection, and player action tracking.',
    fileName: 'CoreProtect-22.4.jar',
    category: 'protection',
  },
  {
    name: 'Dynmap',
    version: '3.7-beta-6',
    author: 'mikeprimm',
    description: 'Real-time dynamic Google Maps-style web viewer for your Minecraft worlds.',
    fileName: 'Dynmap-3.7-beta-6-spigot.jar',
    category: 'world',
  },
  {
    name: 'ViaVersion',
    version: '5.0.0',
    author: 'MyzelYam',
    description: 'Allows newer Minecraft client versions to connect to older server versions smoothly.',
    fileName: 'ViaVersion-5.0.0.jar',
    category: 'performance',
  },
  {
    name: 'Chunky',
    version: '1.4.10',
    author: 'pop4959',
    description: 'Pre-generates world chunks rapidly to eliminate lag spikes caused by exploration.',
    fileName: 'Chunky-1.4.10.jar',
    category: 'performance',
  },
  {
    name: 'ClearLag',
    version: '3.2.2',
    author: 'bob7l',
    description: 'Entity and ground-item reducer, mob limiter, and TPS booster for Paper/Spigot.',
    fileName: 'Clearlag-3.2.2.jar',
    category: 'performance',
  },
  {
    name: 'GeyserMC',
    version: '2.2.0',
    author: 'GeyserMC',
    description: 'Bridge proxy plugin enabling Minecraft Bedrock (Mobile/Console) players to join Java servers.',
    fileName: 'Geyser-Spigot.jar',
    category: 'administration',
  },
];

export const POPULAR_MODS: Omit<MinecraftModItem, 'id' | 'enabled'>[] = [
  {
    name: 'Fabric API',
    version: '0.96.11',
    fileName: 'fabric-api-0.96.11+1.21.jar',
    side: 'both',
    description: 'Essential core library for most Fabric mods and gameplay hooks.',
  },
  {
    name: 'Lithium',
    version: '0.12.1',
    fileName: 'lithium-fabric-0.12.1.jar',
    side: 'server',
    description: 'General-purpose optimization mod improving physics, chunk loading, mob AI, and block ticking.',
  },
  {
    name: 'FerriteCore',
    version: '6.0.1',
    fileName: 'ferritecore-6.0.1-fabric.jar',
    side: 'both',
    description: 'Drastically reduces Minecraft memory usage by optimizing internal data structures.',
  },
  {
    name: 'Krypton',
    version: '0.2.3',
    fileName: 'krypton-0.2.3.jar',
    side: 'server',
    description: 'Optimizes the Minecraft networking stack for smoother packet transfers and lower ping.',
  },
];

/**
 * Initializes standard Minecraft directory and configuration files
 */
export function generateInitialServerFiles(
  serverName: string,
  subdomain: string,
  port: number,
  rconPort: number,
  rconPassword: string,
  loader: MinecraftLoader,
  version: string
): ServerFileItem[] {
  const now = new Date().toISOString();

  const serverProperties = `# Minecraft server properties
# Auto-generated by Flux Hosting Minecraft Platform
# Allocation: 3 GB DDR4 RAM | Xeon E5-2690 v4 | 10 GB NVMe
enable-jmx-monitoring=false
rcon.port=${rconPort}
level-seed=
gamemode=survival
enable-command-block=true
enable-rcon=true
sync-chunk-writes=true
enable-status=true
enable-query=false
level-name=world
motd=§bFlux Hosting §7| §f${serverName} §a[${version}]
query.port=${port}
pvp=true
difficulty=normal
network-compression-threshold=256
require-resource-pack=false
max-tick-time=60000
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
server-ip=0.0.0.0
resource-pack-prompt=
allow-nether=true
server-port=${port}
simulation-distance=8
rcon.password=${rconPassword}
spawn-protection=0
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
spawn-monsters=true
generate-structures=true
hide-online-players=false
`;

  const eulaTxt = `# By changing the setting below to TRUE you are indicating your agreement to the Mojang EULA (https://aka.ms/MinecraftEULA).
# Generated by Flux Hosting
eula=true
`;

  const startScript = `#!/usr/bin/env bash
# Flux Hosting Dedicated Node Minecraft Startup
# Node: Intel Xeon E5-2690 v4 | Memory: 3072M DDR4
echo "[Flux] Initializing Minecraft Server '${serverName}'..."
echo "[Flux] Allocated Port: ${port} | Domain: ${subdomain}.fluxhost.com.tr"
echo "[Flux] Java Runtime: OpenJDK 21 LTS 64-Bit Server VM"

java -Xms1024M -Xmx3072M \\
  -XX:+UseG1GC \\
  -XX:+ParallelRefProcEnabled \\
  -XX:MaxGCPauseMillis=200 \\
  -XX:+UnlockExperimentalVMOptions \\
  -XX:+DisableExplicitGC \\
  -XX:+AlwaysPreTouch \\
  -XX:G1NewSizePercent=30 \\
  -XX:G1MaxNewSizePercent=40 \\
  -XX:G1ReservePercent=20 \\
  -XX:G1HeapWastePercent=5 \\
  -XX:G1MixedGCCountTarget=4 \\
  -XX:InitiatingHeapOccupancyPercent=15 \\
  -XX:G1MixedGCLiveThresholdPercent=90 \\
  -XX:G1RSetUpdatingPauseTimePercent=5 \\
  -XX:SurvivorRatio=32 \\
  -XX:+PerfDisableSharedMem \\
  -XX:MaxTenuringThreshold=1 \\
  -Dusing.aikars.flags=https://mcflags.emc.gs \\
  -Daikars.new.flags=true \\
  -jar server.jar nogui
`;

  const paperYml = `# Paper configuration file
# Flux Hosting optimized defaults
verbose: false
config-version: 28
settings:
  max-joins-per-tick: 5
  track-plugin-scoreboards: false
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
timings:
  enabled: true
  verbose: true
  server-name: "${serverName}"
world-settings:
  default:
    keep-spawn-loaded: false
    generator-settings: {}
    anti-xray:
      enabled: true
      engine-mode: 1
      max-block-height: 64
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - iron_ore
      - diamond_ore
      - ancient_debris
    entity-per-chunk-save-limit:
      experience_orb: 16
      arrow: 16
    despawn-ranges:
      monster:
        soft: 32
        hard: 128
`;

  const opsJson = `[]`;
  const whitelistJson = `[]`;
  const bannedPlayersJson = `[]`;

  return [
    {
      id: 'f_eula',
      name: 'eula.txt',
      path: '/eula.txt',
      type: 'file',
      sizeBytes: Buffer.byteLength(eulaTxt),
      permissions: '0644',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: eulaTxt,
    },
    {
      id: 'f_props',
      name: 'server.properties',
      path: '/server.properties',
      type: 'file',
      sizeBytes: Buffer.byteLength(serverProperties),
      permissions: '0644',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: serverProperties,
    },
    {
      id: 'f_start',
      name: 'start.sh',
      path: '/start.sh',
      type: 'file',
      sizeBytes: Buffer.byteLength(startScript),
      permissions: '0755',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: startScript,
    },
    {
      id: 'f_paper',
      name: 'paper.yml',
      path: '/paper.yml',
      type: 'file',
      sizeBytes: Buffer.byteLength(paperYml),
      permissions: '0644',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: paperYml,
    },
    {
      id: 'f_ops',
      name: 'ops.json',
      path: '/ops.json',
      type: 'file',
      sizeBytes: Buffer.byteLength(opsJson),
      permissions: '0644',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: opsJson,
    },
    {
      id: 'f_whitelist',
      name: 'whitelist.json',
      path: '/whitelist.json',
      type: 'file',
      sizeBytes: Buffer.byteLength(whitelistJson),
      permissions: '0644',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: whitelistJson,
    },
    {
      id: 'f_banned',
      name: 'banned-players.json',
      path: '/banned-players.json',
      type: 'file',
      sizeBytes: Buffer.byteLength(bannedPlayersJson),
      permissions: '0644',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
      content: bannedPlayersJson,
    },
    {
      id: 'd_plugins',
      name: 'plugins',
      path: '/plugins',
      type: 'directory',
      sizeBytes: 4096,
      permissions: '0755',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
    },
    {
      id: 'd_mods',
      name: 'mods',
      path: '/mods',
      type: 'directory',
      sizeBytes: 4096,
      permissions: '0755',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
    },
    {
      id: 'd_world',
      name: 'world',
      path: '/world',
      type: 'directory',
      sizeBytes: 4096,
      permissions: '0755',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
    },
    {
      id: 'd_logs',
      name: 'logs',
      path: '/logs',
      type: 'directory',
      sizeBytes: 4096,
      permissions: '0755',
      owner: 'mcuser',
      group: 'mcuser',
      updatedAt: now,
    },
  ];
}

/**
 * Generates initial console logs for server startup
 */
export function generateInitialStartupLogs(server: MinecraftServerInstance): MinecraftConsoleLog[] {
  const ts = () => new Date().toLocaleTimeString('en-GB', { hour12: false });

  return [
    {
      id: `log_init_0`,
      timestamp: ts(),
      level: 'server',
      message: `[Flux Host] Allocating dedicated resources: 3072 MB DDR4 RAM, Intel Xeon E5-2690 v4 on VDS node ${server.vdsNode.name}...`,
    },
    {
      id: `log_init_1`,
      timestamp: ts(),
      level: 'info',
      thread: 'main',
      message: `Starting Minecraft server version ${server.version} with loader ${server.loader.toUpperCase()}`,
    },
    {
      id: `log_init_2`,
      timestamp: ts(),
      level: 'info',
      thread: 'main',
      message: `Loading properties from server.properties`,
    },
    {
      id: `log_init_3`,
      timestamp: ts(),
      level: 'info',
      thread: 'main',
      message: `Default game type: SURVIVAL | Difficulty: NORMAL | Hardcore: false`,
    },
    {
      id: `log_init_4`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Generating keypair and initializing network layer...`,
    },
    {
      id: `log_init_5`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Starting Minecraft server on 0.0.0.0:${server.port}`,
    },
    {
      id: `log_init_6`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Using 4 threads for Netty event loop`,
    },
    {
      id: `log_init_7`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Preparing level "world"`,
    },
    {
      id: `log_init_8`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Preparing start region for dimension minecraft:overworld`,
    },
    {
      id: `log_init_9`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Time elapsed: 1420 ms`,
    },
    {
      id: `log_init_10`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `RCON running on 0.0.0.0:${server.rconPort}`,
    },
    {
      id: `log_init_11`,
      timestamp: ts(),
      level: 'info',
      thread: 'Server thread',
      message: `Done (2.104s)! For help, type "help"`,
    },
  ];
}

/**
 * Generates live hardware metrics for the Minecraft Server instance
 */
export function generateMinecraftMetrics(server: MinecraftServerInstance): MinecraftServerMetrics {
  const isOnline = server.status === 'online';
  const now = new Date();

  // If server is offline, metrics are zero
  if (!isOnline) {
    return {
      cpuUsagePercent: 0,
      ramUsedMb: 0,
      ramTotalMb: 3072, // 3 GB DDR4
      diskUsedGb: 1.4,
      diskTotalGb: 10, // 10 GB NVMe
      tps: 20.0,
      mspt: 0,
      networkInMbps: 0,
      networkOutMbps: 0,
      uptimeSeconds: 0,
      history: Array.from({ length: 15 }).map((_, i) => ({
        time: new Date(now.getTime() - (15 - i) * 5000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
        cpu: 0,
        ram: 0,
        tps: 20,
      })),
    };
  }

  // Realistic dynamic JVM metrics
  const baseRam = 1450 + (server.plugins?.length || 0) * 45 + (server.mods?.length || 0) * 80;
  const jitterRam = Math.sin(Date.now() / 15000) * 220 + (Math.random() * 80 - 40);
  const ramUsedMb = Math.min(3020, Math.max(1100, Math.round(baseRam + jitterRam)));

  const baseCpu = 8 + (server.onlinePlayersCount || 0) * 6;
  const cpuJitter = Math.sin(Date.now() / 8000) * 6 + (Math.random() * 4);
  const cpuUsagePercent = Math.min(95, Math.max(3.5, Number((baseCpu + cpuJitter).toFixed(1))));

  const tps = Number((19.95 + Math.random() * 0.05).toFixed(2));
  const mspt = Number((11.2 + Math.random() * 4.1).toFixed(1));

  const uptimeSeconds = Math.max(0, Math.floor((Date.now() - (server.uptimeStart || Date.now())) / 1000));

  const history = Array.from({ length: 15 }).map((_, i) => {
    const histTime = new Date(now.getTime() - (14 - i) * 5000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
    const histCpu = Math.max(3, Math.min(95, cpuUsagePercent + Math.sin(i) * 5 + (Math.random() * 4 - 2)));
    const histRam = Math.max(1000, Math.min(3072, ramUsedMb + Math.sin(i * 0.7) * 80));
    return {
      time: histTime,
      cpu: Number(histCpu.toFixed(1)),
      ram: Math.round(histRam),
      tps: 20,
    };
  });

  return {
    cpuUsagePercent,
    ramUsedMb,
    ramTotalMb: 3072, // Fixed 3 GB DDR4 RAM
    diskUsedGb: Number((1.8 + (server.files?.length || 10) * 0.08).toFixed(2)),
    diskTotalGb: 10, // Fixed 10 GB NVMe SSD
    tps,
    mspt,
    networkInMbps: Number((0.4 + (server.onlinePlayersCount || 0) * 0.8 + Math.random() * 0.3).toFixed(2)),
    networkOutMbps: Number((1.2 + (server.onlinePlayersCount || 0) * 2.4 + Math.random() * 0.6).toFixed(2)),
    uptimeSeconds,
    history,
  };
}

/**
 * Handles Minecraft RCON / Console Command Execution
 */
export function executeMinecraftCommand(
  server: MinecraftServerInstance,
  rawCommand: string
): { output: string; exitCode: number; logEntry: MinecraftConsoleLog } {
  const ts = () => new Date().toLocaleTimeString('en-GB', { hour12: false });
  const trimmed = rawCommand.trim();
  const cmd = trimmed.startsWith('/') ? trimmed.slice(1) : trimmed;
  const parts = cmd.split(' ');
  const root = parts[0]?.toLowerCase() || '';
  const args = parts.slice(1);

  if (server.status !== 'online') {
    return {
      output: `Error: Server is ${server.status.toUpperCase()}. You must start the server to run console commands.`,
      exitCode: 1,
      logEntry: {
        id: `log_${Date.now()}`,
        timestamp: ts(),
        level: 'error',
        thread: 'Console',
        message: `Command ignored: Server is not online.`,
      },
    };
  }

  let output = '';

  switch (root) {
    case 'help':
    case '?':
      output = `--- Showing help page 1 of 1 ---
/op <player> : Grants operator status to a player
/deop <player> : Revokes operator status from a player
/whitelist <add|remove|list|on|off> : Manages server whitelist
/ban <player> [reason] : Adds player to banlist
/pardon <player> : Removes player from banlist
/kick <player> [reason] : Kicks a player from the server
/gamemode <survival|creative|adventure|spectator> [player] : Changes gamemode
/tp <target> [destination] : Teleports entities
/time set <day|night|noon|midnight> : Changes world time
/weather <clear|rain|thunder> : Changes weather
/say <message> : Broadcasts message in chat
/tps : Displays server ticks per second and memory
/seed : Displays the world seed
/reload : Reloads server plugins and configurations
/stop : Safely saves and stops the server`;
      break;

    case 'op': {
      const target = args[0];
      if (!target) {
        output = `Usage: /op <player>`;
      } else {
        if (!server.ops.includes(target)) {
          server.ops.push(target);
        }
        output = `[Server] Made ${target} a server operator`;
      }
      break;
    }

    case 'deop': {
      const target = args[0];
      if (!target) {
        output = `Usage: /deop <player>`;
      } else {
        server.ops = server.ops.filter(o => o.toLowerCase() !== target.toLowerCase());
        output = `[Server] Made ${target} no longer a server operator`;
      }
      break;
    }

    case 'whitelist': {
      const sub = args[0]?.toLowerCase();
      const target = args[1];
      if (sub === 'on') {
        server.whitelistEnabled = true;
        output = `[Server] Whitelist is now turned on`;
      } else if (sub === 'off') {
        server.whitelistEnabled = false;
        output = `[Server] Whitelist is now turned off`;
      } else if (sub === 'add') {
        if (!target) {
          output = `Usage: /whitelist add <player>`;
        } else {
          if (!server.whitelist.includes(target)) server.whitelist.push(target);
          output = `[Server] Added ${target} to the whitelist`;
        }
      } else if (sub === 'remove') {
        if (!target) {
          output = `Usage: /whitelist remove <player>`;
        } else {
          server.whitelist = server.whitelist.filter(w => w.toLowerCase() !== target.toLowerCase());
          output = `[Server] Removed ${target} from the whitelist`;
        }
      } else if (sub === 'list') {
        output = `There are ${server.whitelist.length} whitelisted players: ${server.whitelist.join(', ') || 'none'}`;
      } else {
        output = `Usage: /whitelist <on|off|list|add|remove> [player]`;
      }
      break;
    }

    case 'ban': {
      const target = args[0];
      const reason = args.slice(1).join(' ') || 'Banned by operator';
      if (!target) {
        output = `Usage: /ban <player> [reason]`;
      } else {
        server.bannedPlayers = server.bannedPlayers.filter(b => b.username.toLowerCase() !== target.toLowerCase());
        server.bannedPlayers.push({
          username: target,
          reason,
          bannedAt: new Date().toISOString(),
          bannedBy: 'Console',
        });
        server.onlinePlayers = server.onlinePlayers.filter(p => p.username.toLowerCase() !== target.toLowerCase());
        server.onlinePlayersCount = server.onlinePlayers.length;
        output = `[Server] Banned ${target}: ${reason}`;
      }
      break;
    }

    case 'pardon':
    case 'unban': {
      const target = args[0];
      if (!target) {
        output = `Usage: /pardon <player>`;
      } else {
        server.bannedPlayers = server.bannedPlayers.filter(b => b.username.toLowerCase() !== target.toLowerCase());
        output = `[Server] Unbanned ${target}`;
      }
      break;
    }

    case 'kick': {
      const target = args[0];
      const reason = args.slice(1).join(' ') || 'Kicked by an operator';
      if (!target) {
        output = `Usage: /kick <player> [reason]`;
      } else {
        server.onlinePlayers = server.onlinePlayers.filter(p => p.username.toLowerCase() !== target.toLowerCase());
        server.onlinePlayersCount = server.onlinePlayers.length;
        output = `[Server] Kicked ${target}: ${reason}`;
      }
      break;
    }

    case 'tps':
      output = `§6TPS from last 1m, 5m, 15m: §a20.0, §a20.0, §a19.98
§6MSPT: §a12.4ms §7| §6Memory: §a1,450MB / 3,072MB (47%)`;
      break;

    case 'list':
      output = `There are ${server.onlinePlayersCount} of a max of ${server.maxPlayers} players online: ${server.onlinePlayers.map(p => p.username).join(', ') || 'none'}`;
      break;

    case 'say':
      output = `[Server] ${args.join(' ')}`;
      break;

    case 'gamemode': {
      const mode = args[0] || 'survival';
      const target = args[1] || 'Player';
      output = `[Server] Set ${target}'s game mode to ${mode.toUpperCase()}`;
      break;
    }

    case 'time': {
      const action = args[0] || 'set';
      const value = args[1] || 'day';
      output = `[Server] Set the time to ${value}`;
      break;
    }

    case 'weather': {
      const type = args[0] || 'clear';
      output = `[Server] Set the weather to ${type}`;
      break;
    }

    case 'seed':
      output = `[Server] Seed: [-${Math.floor(Math.random() * 899999999999) + 100000000000}]`;
      break;

    case 'reload':
      output = `[Server] Reloading server configuration and plugins...
[Server] Reload complete.`;
      break;

    case 'version':
      output = `This server is running Flux ${server.loader.toUpperCase()} version ${server.version} (Implementing API version ${server.version}-R0.1-SNAPSHOT)`;
      break;

    default:
      output = `[Server] Executed command: ${cmd}`;
      break;
  }

  const logEntry: MinecraftConsoleLog = {
    id: `log_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
    timestamp: ts(),
    level: 'info',
    thread: 'Server thread',
    message: output.replace(/§[0-9a-fk-or]/g, ''),
  };

  return {
    output,
    exitCode: 0,
    logEntry,
  };
}
